version: '3.8'
volumes:
  pg_data:
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    container_name: db
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    # command: python manage.py migrate #&& python csv_loader.py
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
